/** Mockup-matched ultra-premium palette (#6344D4) */
export const HomeTheme = {
  primary: '#6344D4',
  primaryDark: '#4B32AF',
  primaryLight: '#8E78E7',
  primarySoft: '#F3EFFF',
  bg: '#F8F9FC',
  cream: '#FFFBF7',
  creamGrad: ['#FFFCF8', '#FFFBF7', '#FAF8F5'] as const,
  card: '#FFFFFF',
  ink: '#1A1A2E',
  inkSecondary: '#4A4A68',
  inkMuted: '#8E8EA9',
  border: '#E8E8F0',
  borderLight: '#F0F0F5',
  heroBg: ['#F8F4FF', '#F0EAFF', '#E8E0FF'] as const,
  heroBgAlt: ['#EEF2FF', '#E4EAFF', '#D8E2FF'] as const,
  heroCta: ['#8E78E7', '#6344D4', '#5546C9'] as const,
  btnGradient: ['#8E78E7', '#6344D4'] as const,
  partnerGradient: ['#1A0F3C', '#2D2068', '#4B32AF', '#6344D4'] as const,
  progressGradient: ['#A594F0', '#6344D4'] as const,
  success: '#16A34A',
  successLight: '#DCFCE7',
  warningBg: '#FEF9C3',
  warningBorder: '#FDE68A',
  upcomingGradient: ['#FBBF24', '#F59E0B'] as const,
  liveGradient: ['#34D399', '#10B981'] as const,
  liveSectionHeader: ['#1A0F3C', '#2D2068', '#4B32AF'] as const,
  liveCardUpcoming: ['#2D2068', '#4B32AF', '#6D4FD4'] as const,
  liveCardLive: ['#064E3B', '#047857', '#10B981'] as const,
  shadow: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 4,
  },
  shadowPurple: {
    shadowColor: '#6344D4',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 6,
  },
};

export const QUICK_ITEMS = [
  {
    id: 'live',
    title: 'Live Exam',
    subtitle: 'Compete Live',
    route: '/(tabs)/exam' as const,
    image: require('../assets/images/icons/exam.png'),
    iconBg: '#F3EFFF',
    cardGrad: ['#FFF5F5', '#FFFFFF'] as const,
    iconGrad: ['#FCA5A5', '#EF4444'] as const,
  },
  {
    id: 'practice',
    title: 'Practice',
    subtitle: 'Strengthen Skills',
    route: '/(tabs)/practice-categories' as const,
    image: require('../assets/images/icons/exam-time.png'),
    iconBg: '#EFF6FF',
    cardGrad: ['#EFF6FF', '#FFFFFF'] as const,
    iconGrad: ['#93C5FD', '#3B82F6'] as const,
  },
  {
    id: 'quiz',
    title: 'Quiz',
    subtitle: 'Test Yourself',
    route: '/(tabs)/quiz' as const,
    image: require('../assets/images/icons/quiz.png'),
    iconBg: '#ECFDF5',
    cardGrad: ['#ECFDF5', '#FFFFFF'] as const,
    iconGrad: ['#6EE7B7', '#10B981'] as const,
  },
  {
    id: 'timetable',
    title: 'Timetable',
    subtitle: 'Plan Study',
    route: '/(tabs)/timetable' as const,
    image: require('../assets/images/icons/study-time.png'),
    iconBg: '#FFF7ED',
    cardGrad: ['#FFF7ED', '#FFFFFF'] as const,
    iconGrad: ['#FCD34D', '#F59E0B'] as const,
  },
  {
    id: 'books',
    title: 'Books',
    subtitle: 'Exam Books',
    route: '/(tabs)/book-store' as const,
    image: require('../assets/images/icons/book-shop.png'),
    iconBg: '#EEF2FF',
    cardGrad: ['#EEF2FF', '#FFFFFF'] as const,
    iconGrad: ['#A5B4FC', '#6366F1'] as const,
  },
  {
    id: 'partner',
    title: 'Study Partner',
    subtitle: 'Find Buddy',
    route: '/(tabs)/study-partner' as const,
    image: require('../assets/images/icons/online-dating.png'),
    iconBg: '#FDF2F8',
    cardGrad: ['#FDF2F8', '#FFFFFF'] as const,
    iconGrad: ['#F9A8D4', '#EC4899'] as const,
  },
] as const;
