#!/bin/bash
# Quick Fix Script for rncli.h Error (Linux/Mac)
# Usage: ./fix-build.sh

echo "🔧 Fixing rncli.h Error..."

# Step 1: Clean everything
echo ""
echo "📦 Cleaning build artifacts..."
cd android
./gradlew clean
rm -rf app/build
rm -rf app/.cxx
cd ..

# Step 2: Create rncli directory structure
echo ""
echo "📁 Creating rncli directory structure..."
mkdir -p android/app/build/generated/rncli/src/main/jni

# Step 3: Create rncli.h file with basic content
echo ""
echo "📝 Creating rncli.h file..."
cat > android/app/build/generated/rncli/src/main/jni/rncli.h << 'EOF'
#pragma once

// React Native CLI generated header
// This file is auto-generated by React Native Gradle plugin
// If this file exists, it means the build system will use it
EOF

echo ""
echo "✅ Fix applied! Now try building again:"
echo "   cd android"
echo "   ./gradlew bundleRelease"
echo ""
echo "   OR use Expo command:"
echo "   npx expo run:android --variant release"

