# Quick Fix Script for rncli.h Error (Windows)
# Usage: .\fix-build.ps1

Write-Host "🔧 Fixing rncli.h Error..." -ForegroundColor Cyan

# Step 1: Clean everything
Write-Host "`n📦 Cleaning build artifacts..." -ForegroundColor Yellow
Set-Location android
& .\gradlew clean
if (Test-Path "app\build") {
    Remove-Item -Recurse -Force "app\build"
}
if (Test-Path "app\.cxx") {
    Remove-Item -Recurse -Force "app\.cxx"
}
Set-Location ..

# Step 2: Create rncli directory structure
Write-Host "`n📁 Creating rncli directory structure..." -ForegroundColor Yellow
$rncliPath = "android\app\build\generated\rncli\src\main\jni"
New-Item -ItemType Directory -Force -Path $rncliPath | Out-Null

# Step 3: Create rncli.h file with basic content
Write-Host "`n📝 Creating rncli.h file..." -ForegroundColor Yellow
$rncliHeader = @"
#pragma once

// React Native CLI generated header
// This file is auto-generated by React Native Gradle plugin
// If this file exists, it means the build system will use it
"@
$rncliHeader | Out-File -FilePath "$rncliPath\rncli.h" -Encoding UTF8

Write-Host "`n✅ Fix applied! Now try building again:" -ForegroundColor Green
Write-Host "   cd android" -ForegroundColor Cyan
Write-Host "   .\gradlew bundleRelease" -ForegroundColor Cyan
Write-Host "`n   OR use Expo command:" -ForegroundColor Yellow
Write-Host "   npx expo run:android --variant release" -ForegroundColor Cyan

